# Generated by Django 3.1.3 on 2020-11-26 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('d_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('d_number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=100)),
                ('exp', models.CharField(max_length=100)),
                ('d_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.department')),
                ('sup_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdoctors', to='doctor.doctor')),
            ],
        ),
    ]
