# Generated by Django 3.1.3 on 2020-11-29 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guardian',
        ),
    ]
