# Generated by Django 3.1.3 on 2020-11-29 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_delete_guardian'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('first_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=100)),
                ('patient_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'unique_together': {('patient_id', 'first_name')},
            },
        ),
    ]
